service: import-product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::bee-shop-import-csv/uploaded/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::bee-shop-import-csv/uploaded/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: bee-shop-import-csv
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
